[project]
name = "ember-agents"
version = "0.1.0"
description = "The Ember AI agent swarm for intent based cognition and reasoning."
authors = [
    {name = "Tom Daniel", email = "0xtomdaniel@gmail.com"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
package-type = "application"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.4",
]
code-analysis = [
    "ruff>=0.1.9",
]
