[project]
name = "py-project-template"
version = "0.1.0"
description = "Template to use for new Python projects using my selected stack."
authors = [
    {name = "Tom Daniel", email = "0xtomdaniel@gmail.com"},
]
dependencies = [
    "python-dotenv>=1.0.0",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_mode="auto"

[tool.pdm]
package-type = "application"

[tool.pdm.scripts]
#start = "flask run -p 54321"
test = "pytest -s"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.4",
    "pytest-asyncio>=0.23.3",
]
code-analysis = [
    "ruff>=0.1.9",
]
