[project]
name = "py-project-template"
version = "0.1.0"
description = "Template to use for new Python projects using my selected stack"
authors = [
    {name = "Tom Daniel", email = "0xtomdaniel@gmail.com"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
package-type = "application"

[tool.pdm.dev-dependencies]
test = [
    "pytest>=7.4.4",
]
